{
  "formatVersion": "1.1",
  "component": {
    "group": "net.forbricbus",
    "module": "forbricbus-lexforge",
    "version": "8.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "forbricbus-lexforge-8.0.2.jar",
          "url": "forbricbus-lexforge-8.0.2.jar",
          "size": 2199,
          "sha512": "05e07aec140aee767ad985beca2e2ab41ec87dff1432942ba180b40b53bf72066197997a89243d1d5a32b5e8bac2edd657b432d17ca87f4ba2b11e03520a923f",
          "sha256": "423645f2c34601478e9a4c6a404522cc4382dcc9390a5f509d4a3fca0985dc85",
          "sha1": "a1942e09fe3fd6e5ad2145926d0fb704f08c130b",
          "md5": "6b9176884b3a67f04ed1849d60da282f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "strictly": "5.0.4",
            "requires": "5.0.4"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.5-55.0.9_mapped_official_1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "forbricbus-lexforge-8.0.2.jar",
          "url": "forbricbus-lexforge-8.0.2.jar",
          "size": 2199,
          "sha512": "05e07aec140aee767ad985beca2e2ab41ec87dff1432942ba180b40b53bf72066197997a89243d1d5a32b5e8bac2edd657b432d17ca87f4ba2b11e03520a923f",
          "sha256": "423645f2c34601478e9a4c6a404522cc4382dcc9390a5f509d4a3fca0985dc85",
          "sha1": "a1942e09fe3fd6e5ad2145926d0fb704f08c130b",
          "md5": "6b9176884b3a67f04ed1849d60da282f"
        }
      ]
    }
  ]
}
