{
  "formatVersion": "1.1",
  "component": {
    "group": "net.forbricbus",
    "module": "forbricbus-lexforge",
    "version": "8.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "forbricbus-lexforge-8.0.2.jar",
          "url": "forbricbus-lexforge-8.0.2.jar",
          "size": 2202,
          "sha512": "5cb573b54582ab61aa143dc10da2cf40d3104fb6b034964515a9f30bf98432db3bf3a429c1d7dae7838916676179f179e7b40a308d313d9eb8ec5cf843ef9980",
          "sha256": "bac873571900b8145b1a7d7ef3e80cca5ceb28bda8ec114a09d1b819f8af548b",
          "sha1": "f18bb3962fb408951da540ea98b3989f01cfdad9",
          "md5": "1cff3561f1fa54698dcb65cdf6a3e749"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "strictly": "5.0.4",
            "requires": "5.0.4"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.5-55.0.9_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "forbricbus-lexforge-8.0.2.jar",
          "url": "forbricbus-lexforge-8.0.2.jar",
          "size": 2202,
          "sha512": "5cb573b54582ab61aa143dc10da2cf40d3104fb6b034964515a9f30bf98432db3bf3a429c1d7dae7838916676179f179e7b40a308d313d9eb8ec5cf843ef9980",
          "sha256": "bac873571900b8145b1a7d7ef3e80cca5ceb28bda8ec114a09d1b819f8af548b",
          "sha1": "f18bb3962fb408951da540ea98b3989f01cfdad9",
          "md5": "1cff3561f1fa54698dcb65cdf6a3e749"
        }
      ]
    }
  ]
}
